# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiemian.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(828, 618)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(90, 120, 351, 443))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.movie_rank = QtWidgets.QTextEdit(self.groupBox_2)
        self.movie_rank.setObjectName("movie_rank")
        self.verticalLayout_2.addWidget(self.movie_rank)
        self.movie_list = QtWidgets.QTextEdit(self.groupBox_2)
        self.movie_list.setObjectName("movie_list")
        self.verticalLayout_2.addWidget(self.movie_list)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(96, 25, 647, 16))
        self.label_title.setObjectName("label_title")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(90, 40, 731, 70))
        self.groupBox.setObjectName("groupBox")
        self.Edit_input = QtWidgets.QLineEdit(self.groupBox)
        self.Edit_input.setGeometry(QtCore.QRect(15, 33, 611, 21))
        self.Edit_input.setObjectName("Edit_input")
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_search.setGeometry(QtCore.QRect(631, 29, 91, 32))
        self.pushButton_search.setCheckable(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 560, 659, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_star = QtWidgets.QPushButton(Dialog)
        self.pushButton_star.setGeometry(QtCore.QRect(720, 170, 91, 32))
        self.pushButton_star.setObjectName("pushButton_star")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_charactor = QtWidgets.QPushButton(Dialog)
        self.pushButton_charactor.setGeometry(QtCore.QRect(720, 110, 91, 31))
        self.pushButton_charactor.setObjectName("pushButton_charactor")
        self.pushButton_fuzzysearch = QtWidgets.QPushButton(Dialog)
        self.pushButton_fuzzysearch.setGeometry(QtCore.QRect(720, 140, 91, 32))
        self.pushButton_fuzzysearch.setObjectName("pushButton_fuzzysearch")
        self.pushButton_gaibian = QtWidgets.QPushButton(Dialog)
        self.pushButton_gaibian.setGeometry(QtCore.QRect(720, 200, 91, 31))
        self.pushButton_gaibian.setObjectName("pushButton_gaibian")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "电影列表"))
        self.label_title.setText(_translate("Dialog", "电影查询界面"))
        self.groupBox.setTitle(_translate("Dialog", "搜索"))
        self.Edit_input.setPlaceholderText(_translate("Dialog", "请在此输入电影名"))
        self.pushButton_search.setText(_translate("Dialog", "搜索"))
        self.pushButton_star.setText(_translate("Dialog", "收藏"))
        self.pushButton_charactor.setText(_translate("Dialog", "某人作品"))
        self.pushButton_fuzzysearch.setText(_translate("Dialog", "模糊搜索"))
        self.pushButton_gaibian.setText(_translate("Dialog", "名著改编"))
